// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.21
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:372


#include "UATMC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "UATMC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_array\array_cs.cpp:93

UATM::ArrayString_slice *
UATM::ArrayString_dup (const UATM::ArrayString_slice *_tao_src_array)
{
  UATM::ArrayString_slice *_tao_dup_array =
    UATM::ArrayString_alloc ();
  
  if (!_tao_dup_array)
    {
      return static_cast <UATM::ArrayString_slice *> (0);
    }
  
  UATM::ArrayString_copy (_tao_dup_array, _tao_src_array);
  return _tao_dup_array;
}

UATM::ArrayString_slice *
UATM::ArrayString_alloc (void)
{
  UATM::ArrayString_slice *retval = 0;
  ACE_NEW_RETURN (retval, ::TAO::String_Manager[2], 0);
  return retval;
}

void
UATM::ArrayString_free (
    UATM::ArrayString_slice *_tao_slice)
{
  delete [] _tao_slice;
}

void
UATM::ArrayString_copy (
    UATM::ArrayString_slice * _tao_to,
    const UATM::ArrayString_slice *_tao_from)
{
  // Copy each individual element.
  for ( ::CORBA::ULong i0 = 0; i0 < 2; ++i0)
    {
      _tao_to[i0] = _tao_from[i0];
    }
}
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const UATM::flightAuthorization &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.authorization_id) &&
    (strm << _tao_aggregate.flight_id) &&
    (strm << _tao_aggregate.approved_route_id) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.authority.in (), 20)) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.authorization_time.in (), 20)) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.valid_until.in (), 20));
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    UATM::flightAuthorization &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.authorization_id) &&
    (strm >> _tao_aggregate.flight_id) &&
    (strm >> _tao_aggregate.approved_route_id) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.authority.out (), 20)) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.authorization_time.out (), 20)) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.valid_until.out (), 20));
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const UATM::flightChangeRec &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.recommendation_id) &&
    (strm << _tao_aggregate.flight_id) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.change_type.in (), 20)) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.reason.in (), 20)) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.recommended_by.in (), 20)) &&
    (strm << ACE_OutputCDR::from_string (_tao_aggregate.recommendation_time.in (), 20)) &&
    (strm << ::ACE_OutputCDR::from_boolean (_tao_aggregate.request_status));
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    UATM::flightChangeRec &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.recommendation_id) &&
    (strm >> _tao_aggregate.flight_id) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.change_type.out (), 20)) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.reason.out (), 20)) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.recommended_by.out (), 20)) &&
    (strm >> ACE_InputCDR::to_string (_tao_aggregate.recommendation_time.out (), 20)) &&
    (strm >> ::ACE_InputCDR::to_boolean (_tao_aggregate.request_status));
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_array\cdr_op_cs.cpp:162


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const UATM::ArrayString_forany &_tao_array)
{
  CORBA::Boolean _tao_marshal_flag = true;
  
  for ( ::CORBA::ULong i0 = 0; i0 < 2 && _tao_marshal_flag; ++i0)
    {
      _tao_marshal_flag = (strm << ACE_OutputCDR::from_string (_tao_array [i0].in (), 10));
    }

  return _tao_marshal_flag;
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    UATM::ArrayString_forany &_tao_array)
{
  CORBA::Boolean _tao_marshal_flag = true;
  
  for ( ::CORBA::ULong i0 = 0; i0 < 2 && _tao_marshal_flag; ++i0)
    {
      _tao_marshal_flag = (strm >> ACE_InputCDR::to_string (_tao_array [i0].out (), 10));
    }

  return _tao_marshal_flag;
}

TAO_END_VERSIONED_NAMESPACE_DECL



