/* -*- C++ -*- */
/* Generated by C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\bin\opendds_idl version 3.29.1 (ACE version 6.5.21) running on input file UATM.idl */
#ifndef OPENDDS_IDL_GENERATED_UATMTYPESUPPORTIMPL_H_D9F8K5
#define OPENDDS_IDL_GENERATED_UATMTYPESUPPORTIMPL_H_D9F8K5

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 29, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "UATMC.h"
#include "UATMTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: UATM */



/* Begin STRUCT-FWD: flightAuthorization */


/* End STRUCT-FWD: flightAuthorization */


/* Begin STRUCT-FWD: flightChangeRec */


/* End STRUCT-FWD: flightChangeRec */

/* End MODULE: UATM */


/* Begin MODULE: UATM */



/* Begin STRUCT: flightAuthorization */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct UATM_flightAuthorization_xtag {};
template<> UATM_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<UATM_flightAuthorization_xtag>();

template<> UATM_Export
const XTypes::TypeMap& getMinimalTypeMap<UATM_flightAuthorization_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

UATM_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::UATM::flightAuthorization& value);

UATM_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::UATM::flightAuthorization>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

UATM_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::UATM::flightAuthorization& value);

UATM_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::UATM::flightAuthorization>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> UATM_Export
void set_default( ::UATM::flightAuthorization& stru);

UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const ::UATM::flightAuthorization& stru);

UATM_Export
bool operator<<(Serializer& strm, const ::UATM::flightAuthorization& stru);

UATM_Export
bool operator>>(Serializer& strm,  ::UATM::flightAuthorization& stru);

UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::UATM::flightAuthorization>& stru);

UATM_Export
bool operator<<(Serializer& strm, const NestedKeyOnly<const ::UATM::flightAuthorization>& stru);

UATM_Export
bool operator>>(Serializer& strm, const NestedKeyOnly< ::UATM::flightAuthorization>& stru);

template <>
struct MarshalTraits< ::UATM::flightAuthorization> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(87);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::UATM::flightAuthorization&) { return false; }
  static bool from_message_block( ::UATM::flightAuthorization&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const  ::UATM::flightAuthorization> stru);

UATM_Export
bool operator<<(Serializer& strm, KeyOnly<const  ::UATM::flightAuthorization> stru);

UATM_Export
bool operator>>(Serializer& strm, KeyOnly< ::UATM::flightAuthorization> stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace UATM {
/// This structure supports use of std::map with one or more keys.
struct UATM_Export flightAuthorization_OpenDDS_KeyLessThan {
  bool operator()(const  ::UATM::flightAuthorization& v1, const  ::UATM::flightAuthorization& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.authorization_id < v2.authorization_id) return true;
    if (v2.authorization_id < v1.authorization_id) return false;
    return false;
  }
};
}

namespace UATM {
class flightAuthorizationTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::UATM::flightAuthorization> {
  typedef  ::UATM::flightAuthorization MessageType;
  typedef  ::UATM::flightAuthorizationSeq MessageSequenceType;
  typedef  ::UATM::flightAuthorizationSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::UATM::flightAuthorizationTypeSupport TypeSupportType;
  typedef  ::UATM::flightAuthorizationTypeSupportImpl TypeSupportImplType;
  typedef  ::UATM::flightAuthorizationDataWriter DataWriterType;
  typedef  ::UATM::flightAuthorizationDataReader DataReaderType;
  typedef  ::UATM::flightAuthorization_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::UATM::flightAuthorization> KeyOnlyType;
  typedef OpenDDS::DCPS::UATM_flightAuthorization_xtag XtagType;

  static const char* type_name() { return "UATM::flightAuthorization"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace UATM {
class UATM_Export flightAuthorizationTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<flightAuthorization>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<flightAuthorization>
{
public:
  typedef flightAuthorizationTypeSupport TypeSupportType;
  typedef flightAuthorizationTypeSupport::_var_type _var_type;
  typedef flightAuthorizationTypeSupport::_ptr_type _ptr_type;

  flightAuthorizationTypeSupportImpl() {}
  virtual ~flightAuthorizationTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  flightAuthorization* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const flightAuthorization& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const flightAuthorization& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, flightAuthorization_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, flightAuthorization_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static flightAuthorizationTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
UATM_Export
const MetaStruct& getMetaStruct< ::UATM::flightAuthorization>();
UATM_Export
bool gen_skip_over(Serializer& ser,  ::UATM::flightAuthorization*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::flightAuthorization,  ::UATM::flightAuthorization>(DDS::DynamicType_ptr type, const  ::UATM::flightAuthorization& value);

template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::flightAuthorization,  ::UATM::flightAuthorization>(DDS::DynamicType_ptr type,  ::UATM::flightAuthorization& value);

template <>
UATM_Export const  ::UATM::flightAuthorization* get_dynamic_data_adapter_value< ::UATM::flightAuthorization,  ::UATM::flightAuthorization>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: flightAuthorization */

/* End MODULE: UATM */


/* Begin MODULE: UATM */



/* Begin STRUCT: flightChangeRec */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct UATM_flightChangeRec_xtag {};
template<> UATM_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<UATM_flightChangeRec_xtag>();

template<> UATM_Export
const XTypes::TypeMap& getMinimalTypeMap<UATM_flightChangeRec_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

UATM_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::UATM::flightChangeRec& value);

UATM_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::UATM::flightChangeRec>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

UATM_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::UATM::flightChangeRec& value);

UATM_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::UATM::flightChangeRec>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> UATM_Export
void set_default( ::UATM::flightChangeRec& stru);

UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const ::UATM::flightChangeRec& stru);

UATM_Export
bool operator<<(Serializer& strm, const ::UATM::flightChangeRec& stru);

UATM_Export
bool operator>>(Serializer& strm,  ::UATM::flightChangeRec& stru);

UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::UATM::flightChangeRec>& stru);

UATM_Export
bool operator<<(Serializer& strm, const NestedKeyOnly<const ::UATM::flightChangeRec>& stru);

UATM_Export
bool operator>>(Serializer& strm, const NestedKeyOnly< ::UATM::flightChangeRec>& stru);

template <>
struct MarshalTraits< ::UATM::flightChangeRec> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(109);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::UATM::flightChangeRec&) { return false; }
  static bool from_message_block( ::UATM::flightChangeRec&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const  ::UATM::flightChangeRec> stru);

UATM_Export
bool operator<<(Serializer& strm, KeyOnly<const  ::UATM::flightChangeRec> stru);

UATM_Export
bool operator>>(Serializer& strm, KeyOnly< ::UATM::flightChangeRec> stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace UATM {
/// This structure supports use of std::map with one or more keys.
struct UATM_Export flightChangeRec_OpenDDS_KeyLessThan {
  bool operator()(const  ::UATM::flightChangeRec& v1, const  ::UATM::flightChangeRec& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.recommendation_id < v2.recommendation_id) return true;
    if (v2.recommendation_id < v1.recommendation_id) return false;
    return false;
  }
};
}

namespace UATM {
class flightChangeRecTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::UATM::flightChangeRec> {
  typedef  ::UATM::flightChangeRec MessageType;
  typedef  ::UATM::flightChangeRecSeq MessageSequenceType;
  typedef  ::UATM::flightChangeRecSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::UATM::flightChangeRecTypeSupport TypeSupportType;
  typedef  ::UATM::flightChangeRecTypeSupportImpl TypeSupportImplType;
  typedef  ::UATM::flightChangeRecDataWriter DataWriterType;
  typedef  ::UATM::flightChangeRecDataReader DataReaderType;
  typedef  ::UATM::flightChangeRec_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::UATM::flightChangeRec> KeyOnlyType;
  typedef OpenDDS::DCPS::UATM_flightChangeRec_xtag XtagType;

  static const char* type_name() { return "UATM::flightChangeRec"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace UATM {
class UATM_Export flightChangeRecTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<flightChangeRec>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<flightChangeRec>
{
public:
  typedef flightChangeRecTypeSupport TypeSupportType;
  typedef flightChangeRecTypeSupport::_var_type _var_type;
  typedef flightChangeRecTypeSupport::_ptr_type _ptr_type;

  flightChangeRecTypeSupportImpl() {}
  virtual ~flightChangeRecTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  flightChangeRec* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const flightChangeRec& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const flightChangeRec& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, flightChangeRec_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, flightChangeRec_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static flightChangeRecTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
UATM_Export
const MetaStruct& getMetaStruct< ::UATM::flightChangeRec>();
UATM_Export
bool gen_skip_over(Serializer& ser,  ::UATM::flightChangeRec*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::flightChangeRec,  ::UATM::flightChangeRec>(DDS::DynamicType_ptr type, const  ::UATM::flightChangeRec& value);

template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::flightChangeRec,  ::UATM::flightChangeRec>(DDS::DynamicType_ptr type,  ::UATM::flightChangeRec& value);

template <>
UATM_Export const  ::UATM::flightChangeRec* get_dynamic_data_adapter_value< ::UATM::flightChangeRec,  ::UATM::flightChangeRec>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: flightChangeRec */

/* End MODULE: UATM */


/* Begin MODULE: UATM */



/* Begin TYPEDEF: ArrayString */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct UATM_ArrayString_xtag {};
template<> UATM_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<UATM_ArrayString_xtag>();

template<> UATM_Export
const XTypes::TypeMap& getMinimalTypeMap<UATM_ArrayString_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> UATM_Export
void set_default( ::UATM::ArrayString_forany& arr);

UATM_Export
void serialized_size(const Encoding& encoding, size_t& size, const  ::UATM::ArrayString_forany& arr);

UATM_Export
bool operator<<(Serializer& strm, const  ::UATM::ArrayString_forany& arr);

UATM_Export
bool operator>>(Serializer& strm,  ::UATM::ArrayString_forany& arr);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

UATM_Export
bool gen_skip_over(Serializer& ser,  ::UATM::ArrayString_forany*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
struct UATM_ArrayString_dda_tag {};

template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::ArrayString, UATM_ArrayString_dda_tag>(DDS::DynamicType_ptr type, const  ::UATM::ArrayString& value);

template <>
UATM_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::UATM::ArrayString, UATM_ArrayString_dda_tag>(DDS::DynamicType_ptr type,  ::UATM::ArrayString& value);

template <>
UATM_Export const  ::UATM::ArrayString* get_dynamic_data_adapter_value< ::UATM::ArrayString, UATM_ArrayString_dda_tag>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End TYPEDEF: ArrayString */

/* End MODULE: UATM */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_UATMTYPESUPPORTIMPL_H_D9F8K5 */
