#ifndef UATM_IDL
#define UATM_IDL

module UATM {
  struct availabilityInfo;
  struct bookingFlightRequest;
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::availabilityInfo"
#pragma DCPS_DATA_KEY  "UATM::availabilityInfo resource_id"
  struct availabilityInfo {
    string<10> resource_id;
    string<10> resource_type;
    boolean available;
    string<20> skyport_id;
    string<10> availability_time;
  };
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::bookingFlightRequest"
#pragma DCPS_DATA_KEY  "UATM::bookingFlightRequest booking_id"
  struct bookingFlightRequest {
    string<20> booking_id;
    string<20> costumer_id;
    string<20> flight_id;
    string<20> skyport_id;
  };
};
module UATM {
  typedef string<10> ArrayString[2];
};
#endif 
