#ifndef UATM_IDL
#define UATM_IDL

module UATM {
  struct availabilityInfo;
  struct bookingFlightRequest;
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::availabilityInfo"
#pragma DCPS_DATA_KEY  "UATM::availabilityInfo resource_id"
  struct availabilityInfo {
    long resource_id;
    string<20> resource_type;
    boolean status;
    string<20> location;
    string<20> availability_time;
  };
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::bookingFlightRequest"
#pragma DCPS_DATA_KEY  "UATM::bookingFlightRequest booking_id"
  struct bookingFlightRequest {
    long booking_id;
    string<20> customer_id;
    long flight_id;
    string<20> departure_time;
    string<20> arrival_time;
    long route_id;
    boolean request_status;
  };
};
module UATM {
  typedef string<10> ArrayString[2];
};
#endif 
