#ifndef UATM_IDL
#define UATM_IDL

module UATM {
  struct flightAuthorization;
  struct flightChangeRec;
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::flightAuthorization"
#pragma DCPS_DATA_KEY  "UATM::flightAuthorization authorization_id"
  struct flightAuthorization {
    string<20> authorization_id;
    string<20> flight_id;
    string<20> approved_route_id;
    boolean authorization_status;
    string<20> authorization_time;
    string<20> approved_departure_time;
    string<20> approved_arrival_time;
    string<20> tolpad_id;
    string<20> pilot_id;
    string<20> evtol_id;
  };
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::flightChangeRec"
#pragma DCPS_DATA_KEY  "UATM::flightChangeRec recommendation_id"
  struct flightChangeRec {
    long recommendation_id;
    long flight_id;
    string<20> change_type;
    string<20> reason;
    string<20> recommended_by;
    string<20> recommendation_time;
    boolean request_status;
  };
};
module UATM {
  typedef string<10> ArrayString[2];
};
#endif 
