// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.21
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:454

#ifndef _TAO_IDL_UATMS_GK03QC_H_
#define _TAO_IDL_UATMS_GK03QC_H_

#include /**/ "ace/pre.h"

#include "UATMC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/BD_String_SArgument_T.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Fixed_Array_SArgument_T.h"
#include "tao/PortableServer/Var_Array_SArgument_T.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  template<>
  class SArg_Traits< ::UATM::ArrayString_tag>
    : public
        Var_Array_SArg_Traits_T<
            ::UATM::ArrayString_out,
            ::UATM::ArrayString_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::UATM::flightCoordination>
    : public
        Var_Size_SArg_Traits_T<
            ::UATM::flightCoordination,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__SARG_TRAITS_)
#define _CORBA_STRING_20__SARG_TRAITS_

  template<>
  class SArg_Traits<CORBA_STRING_20>
    : public
        BD_String_SArg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::UATM::flightAuthorizationRequest>
    : public
        Var_Size_SArg_Traits_T<
            ::UATM::flightAuthorizationRequest,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__SARG_TRAITS_)
#define _CORBA_STRING_20__SARG_TRAITS_

  template<>
  class SArg_Traits<CORBA_STRING_20>
    : public
        BD_String_SArg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class SArg_Traits< ::UATM::flightRequestInfo>
    : public
        Var_Size_SArg_Traits_T<
            ::UATM::flightRequestInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__SARG_TRAITS_)
#define _CORBA_STRING_20__SARG_TRAITS_

  template<>
  class SArg_Traits<CORBA_STRING_20>
    : public
        BD_String_SArg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_UATM
{
  


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_UATM
{
  


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_UATM
{
  


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_UATM
{
  


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:34

namespace POA_UATM
{
  


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_sh.cpp:65

} // module UATM

#include /**/ "ace/post.h"

#endif /* ifndef */

