// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.21
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:148

#ifndef _TAO_IDL_UATMC_DKXH2G_H_
#define _TAO_IDL_UATMC_DKXH2G_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "UATM_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Array_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/BD_String_Argument_T.h"
#include "tao/Fixed_Array_Argument_T.h"
#include "tao/Var_Array_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 21
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct availabilityInfo;

  typedef
    ::TAO_Var_Var_T<
        availabilityInfo
      >
    availabilityInfo_var;

  typedef
    ::TAO_Out_T<
        availabilityInfo
      >
    availabilityInfo_out;
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct flightRoutesInfo;

  typedef
    ::TAO_Var_Var_T<
        flightRoutesInfo
      >
    flightRoutesInfo_var;

  typedef
    ::TAO_Out_T<
        flightRoutesInfo
      >
    flightRoutesInfo_out;
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct weatherInfo;

  typedef
    ::TAO_Var_Var_T<
        weatherInfo
      >
    weatherInfo_var;

  typedef
    ::TAO_Out_T<
        weatherInfo
      >
    weatherInfo_out;
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct flightAssign;

  typedef
    ::TAO_Var_Var_T<
        flightAssign
      >
    flightAssign_var;

  typedef
    ::TAO_Out_T<
        flightAssign
      >
    flightAssign_out;


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{

  
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct UATM_Export availabilityInfo
  {
    // TAO_IDL - Generated from
    // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:302

    
    typedef availabilityInfo_var _var_type;
    typedef availabilityInfo_out _out_type;
    
    ::CORBA::Long resource_id;
    ::TAO::String_Manager resource_type;
    ::CORBA::Boolean status;
    ::TAO::String_Manager location;
    ::TAO::String_Manager availability_time;
  };


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_array\array_ch.cpp:51

  

  typedef ::TAO::String_Manager ArrayString[2];
  typedef ::TAO::String_Manager ArrayString_slice;
  struct ArrayString_tag {};
  

  typedef
    TAO_VarArray_Var_T<
        ArrayString,
        ArrayString_slice,
        ArrayString_tag
      >
    ArrayString_var;

  typedef
    TAO_Array_Out_T<
        ArrayString,
        ArrayString_var,
        ArrayString_slice,
        ArrayString_tag
      >
    ArrayString_out;

  typedef
    TAO_Array_Forany_T<
        ArrayString,
        ArrayString_slice,
        ArrayString_tag
      >
    ArrayString_forany;

  extern UATM_Export ArrayString_slice *
  ArrayString_alloc (void);

  extern UATM_Export void
  ArrayString_free (
      ArrayString_slice *_tao_slice);
  
  extern UATM_Export ArrayString_slice *
  ArrayString_dup (
      const ArrayString_slice *_tao_slice);
  
  extern UATM_Export void
  ArrayString_copy (
      ArrayString_slice *_tao_to,
      const ArrayString_slice *_tao_from);


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{

  
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct UATM_Export flightRoutesInfo
  {
    // TAO_IDL - Generated from
    // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:302

    
    typedef flightRoutesInfo_var _var_type;
    typedef flightRoutesInfo_out _out_type;
    
    ::CORBA::Long flight_route_id;
    UATM::ArrayString waypoints;
    ::CORBA::Long flight_id;
    ::TAO::String_Manager estimated_time;
    ::CORBA::Boolean status;
  };


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{

  
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct UATM_Export weatherInfo
  {
    // TAO_IDL - Generated from
    // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:302

    
    typedef weatherInfo_var _var_type;
    typedef weatherInfo_out _out_type;
    
    ::CORBA::Long weather_id;
    ::TAO::String_Manager location;
    ::CORBA::Float temperature;
    ::CORBA::Float wind_speed;
    ::TAO::String_Manager weather_condition;
    ::TAO::String_Manager observation_time;
  };


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace UATM
{

  
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct UATM_Export flightAssign
  {
    // TAO_IDL - Generated from
    // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:302

    
    typedef flightAssign_var _var_type;
    typedef flightAssign_out _out_type;
    
    ::CORBA::Long flight_assign_id;
    ::TAO::String_Manager assign_time;
    ::CORBA::Long operator_id;
    ::CORBA::Boolean assign_status;
    UATM::ArrayString resources_id;
  };


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module UATM
// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::UATM::availabilityInfo>
    : public
        Var_Size_Arg_Traits_T<
            ::UATM::availabilityInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

  template<>
  class Arg_Traits< ::UATM::ArrayString_tag>
    : public
        Var_Array_Arg_Traits_T<
            ::UATM::ArrayString_out,
            ::UATM::ArrayString_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::UATM::flightRoutesInfo>
    : public
        Var_Size_Arg_Traits_T<
            ::UATM::flightRoutesInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::UATM::weatherInfo>
    : public
        Var_Size_Arg_Traits_T<
            ::UATM::weatherInfo,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

#if !defined (_CORBA_STRING_10__ARG_TRAITS_)
#define _CORBA_STRING_10__ARG_TRAITS_

  struct CORBA_STRING_10 {};

  template<>
  class Arg_Traits<CORBA_STRING_10>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            10,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:932

  

  template<>
  class Arg_Traits< ::UATM::flightAssign>
    : public
        Var_Size_Arg_Traits_T<
            ::UATM::flightAssign,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_CORBA_STRING_20__ARG_TRAITS_)
#define _CORBA_STRING_20__ARG_TRAITS_

  struct CORBA_STRING_20 {};

  template<>
  class Arg_Traits<CORBA_STRING_20>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            20,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
  template<>
  struct UATM_Export Array_Traits<
      UATM::ArrayString_forany
    >
  {
    static void free (
        UATM::ArrayString_slice * _tao_slice);
    static UATM::ArrayString_slice * dup (
        const UATM::ArrayString_slice * _tao_slice);
    static void copy (
        UATM::ArrayString_slice * _tao_to,
        const UATM::ArrayString_slice * _tao_from);
    static UATM::ArrayString_slice * alloc (void);
    static void zero (
        UATM::ArrayString_slice * _tao_slice);
  };
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:42


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

UATM_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const UATM::availabilityInfo &);
UATM_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, UATM::availabilityInfo &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_array\cdr_op_ch.cpp:98


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

UATM_Export CORBA::Boolean operator<< (TAO_OutputCDR &strm, const UATM::ArrayString_forany &_tao_array);
UATM_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, UATM::ArrayString_forany &_tao_array);

TAO_END_VERSIONED_NAMESPACE_DECL

// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:42


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

UATM_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const UATM::flightRoutesInfo &);
UATM_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, UATM::flightRoutesInfo &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:42


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

UATM_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const UATM::weatherInfo &);
UATM_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, UATM::weatherInfo &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:42


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

UATM_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const UATM::flightAssign &);
UATM_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, UATM::flightAssign &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\ongio_1lak36v\Downloads\OpenDDS-3.29.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:1649

#if defined (__ACE_INLINE__)
#include "UATMC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

