#ifndef UATM_IDL
#define UATM_IDL

module UATM {
  struct flightCoordination;
  struct flightAuthorizationRequest;
  struct flightRequestInfo;
};
module UATM {
  typedef string<10> ArrayString[2];
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::flightCoordination"
#pragma DCPS_DATA_KEY  "UATM::flightCoordination coordination_id"
  struct flightCoordination {
    string<20> coordination_id;
    string<20> flight_id;
    string<20> skyport_id;
    string<20> evtol_id;
    string<20> pilot_id;
    string<20> route_id;
    string<20> weather_id;
  };
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::flightAuthorizationRequest"
#pragma DCPS_DATA_KEY  "UATM::flightAuthorizationRequest auth_request_id"
  struct flightAuthorizationRequest {
    string<20> auth_request_id;
    string<20> flight_id;
    string<20> departure_skyport_id;
    string<20> destination_skyport_id;
    string<20> departure_time;
    string<20> pilot_id;
    string<20> evtol_id;
  };
};
module UATM {

#pragma DCPS_DATA_TYPE "UATM::flightRequestInfo"
  struct flightRequestInfo {
    string<20> request_id;
    string<20> flight_id;
    string<20> departure_skyport_id;
    string<20> destination_skyport_id;
    string<20> departure_time;
    string<20> pilot_id;
    string<20> evtol_id;
  };
};
#endif 
